<a href="https://colab.research.google.com/github/LuciferX45/Deep-Learning-Labs/blob/main/DL_LAB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DL LAB 4**
# **Gautam Padhi**
# I034 B2
# BTech AI SEM V


In [ ]:
# import libraries and dataset
import tensorflow as tf
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
# scaling the features using standard scaler 
from sklearn.preprocessing import StandardScaler
scaller=StandardScaler()
data.iloc[:,[0,1]]=scaller.fit_transform(data.iloc[:,[0,1]])
data

Pregnancies   Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0       0.639947  0.848324             72             35        0  33.6   
1      -0.844885 -1.123396             66             29        0  26.6   
2       1.233880  1.943724             64              0        0  23.3   
3      -0.844885 -0.998208             66             23       94  28.1   
4      -1.141852  0.504055             40             35      168  43.1   
..           ...       ...            ...            ...      ...   ...   
763     1.827813 -0.622642             76             48      180  32.9   
764    -0.547919  0.034598             70             27        0  36.8   
765     0.342981  0.003301             72             23      112  26.2   
766    -0.844885  0.159787             60              0        0  30.1   
767    -0.844885 -0.873019             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
# splitting into train and test data
from sklearn.model_selection import train_test_split
X,Y=data.iloc[:,[0,1]],data.iloc[:,2]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,)

In [ ]:
# building a three layer neural network
# apt loss functions are used.
model=tf.keras.Sequential()
model.add(tf.keras.layers.Dense(16,activation='relu',input_shape=(2,)))
model.add(tf.keras.layers.Dense(16,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [ ]:
# describe the layers of the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                48        
                                                                 
 dense_1 (Dense)             (None, 16)                272       
                                                                 
 dense_2 (Dense)             (None, 1)                 17        
                                                                 
Total params: 337
Trainable params: 337
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# using adam as the optimizer
opt = tf.keras.optimizers.Adam(learning_rate=0.001)

model.compile(loss='binary_crossentropy',optimizer=opt,metrics=['accuracy'])

In [ ]:
callback=tf.keras.callbacks.EarlyStopping(
    monitor="accuracy",
    min_delta=0,
    patience=100,
    verbose=0,
    mode="auto",
    baseline=None,
    restore_best_weights=True,
)

In [ ]:
# compile and fit the model to the training dataset
model.fit(X_train,Y_train,epochs=1000,callbacks=[callback])

Epoch 1/1000
20/20 [==============================] - 1s 2ms/step - loss: 0.1567 - accuracy: 0.0212
Epoch 2/1000
20/20 [==============================] - 0s 2ms/step - loss: -22.1903 - accuracy: 0.0016
Epoch 3/1000
20/20 [==============================] - 0s 2ms/step - loss: -45.2226 - accuracy: 0.0000e+00
Epoch 4/1000
20/20 [==============================] - 0s 2ms/step - loss: -71.6071 - accuracy: 0.0000e+00
Epoch 5/1000
20/20 [==============================] - 0s 2ms/step - loss: -104.7564 - accuracy: 0.0000e+00
Epoch 6/1000
20/20 [==============================] - 0s 2ms/step - loss: -147.1852 - accuracy: 0.0000e+00
Epoch 7/1000
20/20 [==============================] - 0s 2ms/step - loss: -202.3969 - accuracy: 0.0000e+00
Epoch 8/1000
20/20 [==============================] - 0s 2ms/step - loss: -276.7598 - accuracy: 0.0000e+00
Epoch 9/1000
20/20 [==============================] - 0s 2ms/step - loss: -375.0218 - accuracy: 0.0000e+00
Epoch 10/1000
20/20 [==============================

In [ ]:
# get predicitons from the model on the test dataset
ypred=model.predict(X_test)

In [ ]:
Y_test=np.array(Y_test).reshape(-1,1)

In [ ]:
# find the mean square error of the model
MSE=sum(((Y_test-ypred)**2))/(2*len(ypred))

In [ ]:
MSE

array([2687.88310308])

In [ ]:
# using other optimizers
opt = tf.keras.optimizers.SGD(learning_rate=0.002)
model.compile(loss='binary_crossentropy',optimizer=opt,metrics=['accuracy'])

callback=tf.keras.callbacks.EarlyStopping(
    monitor="accuracy",
    min_delta=0,
    patience=100,
    verbose=0,
    mode="auto",
    baseline=None,
    restore_best_weights=True,
)

In [ ]:
model.fit(X_train,Y_train,epochs=1000,callbacks=[callback])

Epoch 1/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0000e+00 
Epoch 2/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 3/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 4/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 5/1000
20/20 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.0505
Epoch 6/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 7/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 8/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 9/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 10/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 11/1000
20/20 [===

In [ ]:
ypred=model.predict(X_test)

In [ ]:
Y_test=np.array(Y_test).reshape(-1,1)

In [ ]:
MSE2=sum(((Y_test-ypred)**2))/(2*len(ypred))

In [ ]:
MSE2

array([nan])

In [ ]:
opt = tf.keras.optimizers.Adagrad(learning_rate=0.001)

In [ ]:
model.compile(loss='binary_crossentropy',optimizer=opt,metrics=['accuracy'])

callback=tf.keras.callbacks.EarlyStopping(
    monitor="accuracy",
    min_delta=0,
    patience=100,
    verbose=0,
    mode="auto",
    baseline=None,
    restore_best_weights=True,
)

In [ ]:
model.fit(X_train,Y_train,epochs=1000,callbacks=[callback])


Epoch 1/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 2/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 3/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 4/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 5/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 6/1000
20/20 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.0505
Epoch 7/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 8/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 9/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 10/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 11/1000
20/20 [========

In [ ]:
ypred=model.predict(X_test)
Y_test=np.array(Y_test).reshape(-1,1)
MSE3=sum(((Y_test-ypred)**2))/(2*len(ypred))

In [ ]:
MSE3

array([nan])

In [ ]:
opt = tf.keras.optimizers.Adamax(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=opt,metrics=['accuracy'])

callback=tf.keras.callbacks.EarlyStopping(
    monitor="accuracy",
    min_delta=0,
    patience=100,
    verbose=0,
    mode="auto",
    baseline=None,
    restore_best_weights=True,
)

In [ ]:
model.fit(X_train,Y_train,epochs=1000,callbacks=[callback])


Epoch 1/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 2/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 3/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 4/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 5/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 6/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 7/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 8/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 9/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 10/1000
20/20 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0505
Epoch 11/1000
20/20 [========

In [ ]:
ypred=model.predict(X_test)
Y_test=np.array(Y_test).reshape(-1,1)
MSE4=sum(((Y_test-ypred)**2))/(2*len(ypred))

In [ ]:
MSE4

array([nan])

In [ ]:
d = {'Adam':MSE[0],'SGD':MSE2[0],'Adagrad':MSE3[0],'Adamax':MSE4[0]}

In [ ]:
type(d)

dict

In [ ]:
df_mse = pd.DataFrame(d,index=[0])

In [ ]:
df_mse

Adam  SGD  Adagrad  Adamax
0  2687.883103  NaN      NaN     NaN

**CONCLUSION**

In the above displayed data frame, we can observe that using different optimizers gives accuracy of 0.08 in all cases, with values differing only after few decimal places. 

Other hyperparameters were also adjusted, which only led to the model overfitting.